version: "3.9"

services:
  logger:
    container_name: notification-service
    image: search-engine/notification:latest
    networks:
      - search-engine
    env_file:
      - env.txt
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M

networks:
  search-engine:
    driver: bridge
    name: search-engine-network
    external: true